server {
    listen 80;
    
    resolver 127.0.0.11 valid=30s;

    location /projeto-korp {
        set $upstream app:8080;
        proxy_pass http://$upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
