{
 "title": "HTTP Server Projeto Korp",
 "tags": [ "korp" ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Disponibilidade do Servico",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"korp\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Taxa de Requisicoes por segundo",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "req/s" }
   ]
  },
  {
   "title": "Total Acumulado de Requisicoes",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Total HTTP Requests (Gráfico)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{method}}" }
   ]
  }
 ]
}